services:
  postgres:
    image: postgres:16-alpine
    container_name: piedrazul-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Variable POSTGRES_PASSWORD es requerida}
      POSTGRES_DB: ${POSTGRES_DB:-piedrazul}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/postgres/init:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: piedrazul-keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER:-postgres}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:?Variable POSTGRES_PASSWORD es requerida}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:?Variable KEYCLOAK_ADMIN_PASSWORD es requerida}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./backend/keycloak:/opt/keycloak/data/import

  redis:
    image: redis:7-alpine
    container_name: piedrazul-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: piedrazul-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:?Variable RABBITMQ_PASS es requerida}

volumes:
  postgres_data:
