sonar.projectKey=piedrazul-citas-app
sonar.projectName=piedrazul-citas-app
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/backend/**,**/*.test.ts
sonar.host.url=http://localhost:9000
sonar.token=sqp_7cf0a92bb1488adc1d26fc93ac7f59fb6cedf195
sonar.javascript.node.maxspace=512